//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 

using System.Security.Cryptography.X509Certificates;

#pragma warning disable 1591

namespace signDataService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="signDataServiceSOAP", Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class signDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback prepSignDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifySignedDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback noOpOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
		public signDataService(X509Certificate clientCert, string url)
		{
			this.Url = url;
			ClientCertificates.Add(clientCert);
		}
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event prepSignDataCompletedEventHandler prepSignDataCompleted;
        
        /// <remarks/>
        public event verifySignedDataCompletedEventHandler verifySignedDataCompleted;
        
        /// <remarks/>
        public event noOpCompletedEventHandler noOpCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.symantec.com/pkiservices/2011/11/sign/signDataOperations/prepSignD" +
            "ataRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PrepSignDataResponse", Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
        public PrepSignDataResponse prepSignData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")] PrepSignDataRequest PrepSignDataRequest) {
            object[] results = this.Invoke("prepSignData", new object[] {
                        PrepSignDataRequest});
            return ((PrepSignDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void prepSignDataAsync(PrepSignDataRequest PrepSignDataRequest) {
            this.prepSignDataAsync(PrepSignDataRequest, null);
        }
        
        /// <remarks/>
        public void prepSignDataAsync(PrepSignDataRequest PrepSignDataRequest, object userState) {
            if ((this.prepSignDataOperationCompleted == null)) {
                this.prepSignDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprepSignDataOperationCompleted);
            }
            this.InvokeAsync("prepSignData", new object[] {
                        PrepSignDataRequest}, this.prepSignDataOperationCompleted, userState);
        }
        
        private void OnprepSignDataOperationCompleted(object arg) {
            if ((this.prepSignDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.prepSignDataCompleted(this, new prepSignDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.symantec.com/pkiservices/2011/11/sign/signDataOperations/verifySig" +
            "nedDataRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("VerifySignedDataResponse", Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
        public VerifySignedDataResponse verifySignedData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")] VerifySignedDataRequest VerifySignedDataRequest) {
            object[] results = this.Invoke("verifySignedData", new object[] {
                        VerifySignedDataRequest});
            return ((VerifySignedDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void verifySignedDataAsync(VerifySignedDataRequest VerifySignedDataRequest) {
            this.verifySignedDataAsync(VerifySignedDataRequest, null);
        }
        
        /// <remarks/>
        public void verifySignedDataAsync(VerifySignedDataRequest VerifySignedDataRequest, object userState) {
            if ((this.verifySignedDataOperationCompleted == null)) {
                this.verifySignedDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifySignedDataOperationCompleted);
            }
            this.InvokeAsync("verifySignedData", new object[] {
                        VerifySignedDataRequest}, this.verifySignedDataOperationCompleted, userState);
        }
        
        private void OnverifySignedDataOperationCompleted(object arg) {
            if ((this.verifySignedDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifySignedDataCompleted(this, new verifySignedDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.symantec.com/pkiservices/2011/11/sign/signDataOperations/noOpReque" +
            "st", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ToBeSignedClientPKCS7BlobType", Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
        public ToBeSignedClientPKCS7BlobType noOp([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")] ToBeSignedPKCS7BlobType ToBeSignedPKCS7BlobType) {
            object[] results = this.Invoke("noOp", new object[] {
                        ToBeSignedPKCS7BlobType});
            return ((ToBeSignedClientPKCS7BlobType)(results[0]));
        }
        
        /// <remarks/>
        public void noOpAsync(ToBeSignedPKCS7BlobType ToBeSignedPKCS7BlobType) {
            this.noOpAsync(ToBeSignedPKCS7BlobType, null);
        }
        
        /// <remarks/>
        public void noOpAsync(ToBeSignedPKCS7BlobType ToBeSignedPKCS7BlobType, object userState) {
            if ((this.noOpOperationCompleted == null)) {
                this.noOpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnoOpOperationCompleted);
            }
            this.InvokeAsync("noOp", new object[] {
                        ToBeSignedPKCS7BlobType}, this.noOpOperationCompleted, userState);
        }
        
        private void OnnoOpOperationCompleted(object arg) {
            if ((this.noOpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.noOpCompleted(this, new noOpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class PrepSignDataRequest {
        
        private string clientTransactionIDField;
        
        private SignDataInfoType signDataInfoField;
        
        private byte[] toBeSignDataField;
        
        private string versionField;
        
        /// <remarks/>
        public string clientTransactionID {
            get {
                return this.clientTransactionIDField;
            }
            set {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        public SignDataInfoType signDataInfo {
            get {
                return this.signDataInfoField;
            }
            set {
                this.signDataInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] toBeSignData {
            get {
                return this.toBeSignDataField;
            }
            set {
                this.toBeSignDataField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class SignDataInfoType {
        
        private string descriptionField;
        
        private CertificateFilterType certificateFilterField;
        
        private HashAlgorithmType hashAlgorithmField;
        
        private string urlFilterField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public CertificateFilterType certificateFilter {
            get {
                return this.certificateFilterField;
            }
            set {
                this.certificateFilterField = value;
            }
        }
        
        /// <remarks/>
        public HashAlgorithmType hashAlgorithm {
            get {
                return this.hashAlgorithmField;
            }
            set {
                this.hashAlgorithmField = value;
            }
        }
        
        /// <remarks/>
        public string urlFilter {
            get {
                return this.urlFilterField;
            }
            set {
                this.urlFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class CertificateFilterType {
        
        private string[] profileIDFilterSetField;
        
        private UserFilterType[] userFilterSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("profileOID", IsNullable=false)]
        public string[] profileIDFilterSet {
            get {
                return this.profileIDFilterSetField;
            }
            set {
                this.profileIDFilterSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("userFilter", IsNullable=false)]
        public UserFilterType[] userFilterSet {
            get {
                return this.userFilterSetField;
            }
            set {
                this.userFilterSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class UserFilterType {
        
        private UserAttributeNameType userAttributeNameField;
        
        private string userAttributeValueField;
        
        private bool ignoreCaseField;
        
        private bool ignoreCaseFieldSpecified;
        
        /// <remarks/>
        public UserAttributeNameType userAttributeName {
            get {
                return this.userAttributeNameField;
            }
            set {
                this.userAttributeNameField = value;
            }
        }
        
        /// <remarks/>
        public string userAttributeValue {
            get {
                return this.userAttributeValueField;
            }
            set {
                this.userAttributeValueField = value;
            }
        }
        
        /// <remarks/>
        public bool ignoreCase {
            get {
                return this.ignoreCaseField;
            }
            set {
                this.ignoreCaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ignoreCaseSpecified {
            get {
                return this.ignoreCaseFieldSpecified;
            }
            set {
                this.ignoreCaseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public enum UserAttributeNameType {
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        UID,
        
        /// <remarks/>
        rfc822Name,
        
        /// <remarks/>
        UPN,
        
        /// <remarks/>
        DNSName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public enum HashAlgorithmType {
        
        /// <remarks/>
        sha512,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class PrepSignDataResponse {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private byte[] pkcs7SignedBlobField;
        
        private string versionField;
        
        /// <remarks/>
        public string clientTransactionID {
            get {
                return this.clientTransactionIDField;
            }
            set {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string serverTransactionID {
            get {
                return this.serverTransactionIDField;
            }
            set {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pkcs7SignedBlob {
            get {
                return this.pkcs7SignedBlobField;
            }
            set {
                this.pkcs7SignedBlobField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class VerifySignedDataRequest {
        
        private string clientTransactionIDField;
        
        private byte[] clientPkcs7SignedBlobField;
        
        private string versionField;
        
        /// <remarks/>
        public string clientTransactionID {
            get {
                return this.clientTransactionIDField;
            }
            set {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] clientPkcs7SignedBlob {
            get {
                return this.clientPkcs7SignedBlobField;
            }
            set {
                this.clientPkcs7SignedBlobField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class VerifySignedDataResponse {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private StatusType statusField;
        
        private string versionField;
        
        /// <remarks/>
        public string clientTransactionID {
            get {
                return this.clientTransactionIDField;
            }
            set {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string serverTransactionID {
            get {
                return this.serverTransactionIDField;
            }
            set {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public enum StatusType {
        
        /// <remarks/>
        SUCCESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class ToBeSignedPKCS7BlobType {
        
        private SignDataInfoType signDataInfoField;
        
        private string organizationField;
        
        private string requestIdField;
        
        private byte[] hashValueField;
        
        private string versionField;
        
        /// <remarks/>
        public SignDataInfoType signDataInfo {
            get {
                return this.signDataInfoField;
            }
            set {
                this.signDataInfoField = value;
            }
        }
        
        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] hashValue {
            get {
                return this.hashValueField;
            }
            set {
                this.hashValueField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.symantec.com/pkiservices/2011/11/sign")]
    public partial class ToBeSignedClientPKCS7BlobType {
        
        private byte[] pkcs7SignedBlobField;
        
        private byte[] toBeSignDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pkcs7SignedBlob {
            get {
                return this.pkcs7SignedBlobField;
            }
            set {
                this.pkcs7SignedBlobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] toBeSignData {
            get {
                return this.toBeSignDataField;
            }
            set {
                this.toBeSignDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void prepSignDataCompletedEventHandler(object sender, prepSignDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class prepSignDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal prepSignDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PrepSignDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PrepSignDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void verifySignedDataCompletedEventHandler(object sender, verifySignedDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifySignedDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifySignedDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifySignedDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifySignedDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void noOpCompletedEventHandler(object sender, noOpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class noOpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal noOpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ToBeSignedClientPKCS7BlobType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ToBeSignedClientPKCS7BlobType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591